### ISSUE TITLE
Drag and Drop

### ISSUE THREAD

**Issue by Penkethboy** [AnthonyMusgrove/Emby-ScripterX#26]
if you are going to add drag and drop to the parameters section can you add " " around the non integer/number variables or just all variables which would be easier i suspect

Also

1. can you also add a file picker dialog to pick the script file

1.1 and on basis of script file extension add "-File" , /d etc etc

2. Make Interpreter a drop down list of supported interpreters powershell, pwsh, cmd etc

with all the above this would eliminate most of the typing and be mostly mouse driven

**Comment by AnthonyMusgrove** [comment]
This one is in progress mate, I love these ideas :)  I'm just researching the Emby API for how to implement the filepicker dialog (looking at the add library functions etc)!

**Comment by AnthonyMusgrove** [comment]
Hey mate, I'm still working on this one.  It's just a bit fiddly but it will work I promise :)

**Comment by AnthonyMusgrove** [comment]
Getting closer :) 

![MouseFriendlyInterface](https://user-images.githubusercontent.com/55648663/84104391-e7bd2c80-aa58-11ea-84ee-9a22fcb605d1.png)

**Comment by AnthonyMusgrove** [comment]
Im currently devoting 99.9% effort in getting this component complete.  It involves a fair bit of interface coding and testing which is great, because the actions interface code is currently bulky (works great, but bulky), so it will be a great therapeutic experience for me.  Tonight ill be sitting down to map the rest of it out, it will be aweaome.
