### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by Slugger** [AnthonyMusgrove/Emby-ScripterX#31]
**Describe the bug**
Created a basic test package, in a newly built dev env (fresh docker install, latest docker, no media, separate from my prod server, etc., latest ScripterX installed).

**To Reproduce**

1. Install latest Emby docker
2. Install latest ScripterX
3. Create a basic package following wiki instructions
4. Attempt to install package zip

**Expected behavior**
Uploaded package zip is installed and deployed

**Screenshots**
![image](https://user-images.githubusercontent.com/351737/84210452-bbb8a000-aa86-11ea-8899-d82809a49783.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Chrome
 - 83

**Smartphone (please complete the following information):**
n/a

** Server Details **
 - Debian 10
 - Docker image: linuxserver/emby (latest 4.4.3)
 - latest ScripterX installed

**Additional context**
After the error is reported back, I can go into the docker and go to the directory it shows in the error message and it exists and my zip file has been exploded there.  I can see my json and js files sitting there.  So the zip was accepted and unzipped on the server, but then I get the error shown.

**Comment by AnthonyMusgrove** [comment]
Thank you mate, I'll check this out now and see if its just a permissions or path issue with docker

**Comment by AnthonyMusgrove** [comment]
Thank you so much for reporting this issue.  It was an issue on my end.  Now rectified in v3.0.3.4 (now up on Emby Catalog), please update and this issue will be resolved :)

* Rectified reported [<a is="emby-linkbutton" target= '_blank' href="https://github.com/AnthonyMusgrove/Emby-ScripterX/issues/31" class="button-link emby-button">Github Issue#31</a>] where packages couldn't install.  This was due to the Package Installer not successfully checking for the 'Packages'
directory before attempting to move files into the package's repository.

**Comment by Slugger** [comment]
Ok, got past this problem, but my event handler isn't being called.  I'll open another ticket for that shortly.  I was also going to open a ticket to discuss how I might get package settings into my package.  But when I got the package installed it looks like you've already thought of this.  There is a settings icon for my package and when I click I get told that my package doesn't have a config interface.  Indeed it doesn't.  I didn't see any mention of that in the packages wiki.  So... how do I create a config interface for my package?  And how do I access that config in my js? :)
