### ISSUE TITLE
When using web:get, Call variables directly in URL

### ISSUE THREAD

**Issue by fkueyu** [AnthonyMusgrove/Emby-ScripterX#57]
When using Web: get, can I use existing variables in URLs? If so, how can I call it? If not, consider adding this feature?

**Comment by AnthonyMusgrove** [comment]
Hi guys, let me check this one out, sounds like a great idea which I am absolutely keen to implement for you.

**Comment by AnthonyMusgrove** [comment]
![image](https://user-images.githubusercontent.com/55648663/164019840-b8ae3b20-8b2f-49bf-8a49-ab4843a52df4.png)

So for example, using WEB:GET, the URL to 'get' is stored in the 'script' field, and now supports tokens being used, ie  https://myurl.com/?action=play&userid=%user.id%&itemid=%item.id% for example, will produce something like  https://myurl.com/?action=play&userid=anthony&itemid=6992  

This is at the request of @fkueyu  on GitHub

So as of 4.0.0.3 this will be available, and all new releases of ScripterX require the Beta version of Emby (4.7.35+) to be installed otherwise ScripterX new releases will not function properly (if at all).

**Comment by fkueyu** [comment]
Great, thank you

**Comment by fkueyu** [comment]
![微信截图_20220519111934](https://user-images.githubusercontent.com/9735657/169197245-bf4f3f38-e003-4afb-99e5-639dd410483f.png)

@AnthonyMusgrove request Run text box wrapping support
